export default {
  SET_INITIAL_DATA: "SET_INITIAL_DATA",
  SWAP_SOVEREIGN_STATES_FILTER: "SWAP_SOVEREIGN_STATES_FILTER",
  CHANGE_REGION_FILTER: "CHANGE_REGION_FILTER",
  CHANGE_SUBREGION_FILTER: "CHANGE_SUBREGION_FILTER",
  SEARCH: "SEARCH",
  CHANGE_SORTING: "CHANGE_SORTING",
  SORT: "SORT"
}