export default {
    SET_ALL_COUNTRIES: "FETCH_ALL_COUNTRIES",
    SWAP_SOVEREIGN_STATES_FILTER: "SWAP_SOVEREIGN_STATES_FILTER",
    CHANGE_REGION_FILTER: "CHANGE_REGION_FILTER",
    SEARCH: "SEARCH"
}